version: '3.1'

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - caddy
      - backend
    depends_on:
      - mariadb

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=https://phpmyadmin.${DOMAIN_NAME}
      - PMA_HOST=mariadb
    networks:
      - caddy
      - backend
    depends_on:
      - mariadb
    

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend


  caddy:
    container_name: caddy
    image: caddy
    build:
      context: ./srcs/caddy
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        CLOUDFLARE_KEY: ${CLOUDFLARE_KEY}
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ='Europe/Paris'
      - CADDY_INGRESS_NETWORKS=caddy
      - CADDY_DOCKER_CADDYFILE_PATH=/etc/caddy/Caddyfile
    restart: always
    networks:
      - caddy
    depends_on:
      - wordpress
      - phpmyadmin


volumes:
  wordpress:
  db:
  caddy:

networks:
  caddy:
    driver: bridge
  backend:
    driver: bridge