version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    environment:
      DB_HOST: mariadb
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - caddy
      - backend
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=https://phpmyadmin.${DOMAIN_NAME}
    networks:
      - caddy
      - backend
    depends_on:
      - mariadb
    

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend


  caddy:
    container_name: caddy
    image: iarekylew00t/caddy-cloudflare:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CLOUDFLARE_KEY=${CLOUDFLARE_KEY}
    volumes:
      - caddy:/data
    restart: always
    networks:
      - caddy
    depends_on:
      - wordpress
      - phpmyadmin


volumes:
  wordpress:
  db:
  caddy:

networks:
  caddy:
    driver: bridge
  backend:
    driver: bridge